### ISSUE TITLE
Question about 3.Docker Build and Launch

### ISSUE THREAD

**Issue by chengzihencai** [beyondli/Yolo_on_Jetson#1]
In step.3 :Docker Build and Launch,It is recommended to use Docker Run these commands.And there is one command:#cd outside Yolo_on_Jetson to install pytorch-quantization
Should I run this command and other commands in step.3 in docker?

**Comment by beyondli** [comment]
all commands should be run inside docker

**Comment by chengzihencai** [comment]
Thanks.
And in 8.3 ，I tried to` run deepstream-app -c deepstream_app_config.txt`,an error was report:
`Opening in BLOCKING MODE

Using winsys: x11
0:00:04.861713015 10390     0x3394e2f0 INFO                 nvinfer gstnvinfer.cpp:638:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1900> [UID = 1]: deserialized trt engine from :/home/lcfc/Desktop/Yolo_on_Jetson/deepstream/models/yolov5s_fp32.engine
INFO: [Implicit Engine Info]: layers num: 5
0   INPUT  kFLOAT images          3x640x640       
1   OUTPUT kFLOAT 752             3x80x80x17     
2   OUTPUT kFLOAT 818             3x40x40x17     
3   OUTPUT kFLOAT 884             3x20x20x17     
4   OUTPUT kFLOAT output          25200x17       

0:00:04.862091838 10390     0x3394e2f0 INFO                 nvinfer gstnvinfer.cpp:638:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2004> [UID = 1]: Use deserialized engine model: /home/lcfc/Desktop/Yolo_on_Jetson/deepstream/models/yolov5s_fp32.engine
0:00:05.105739424 10390     0x3394e2f0 INFO                 nvinfer gstnvinfer_impl.cpp:313:notifyLoadModelStatus:<primary_gie> [UID 1]: Load new model:/home/lcfc/Desktop/Yolo_on_Jetson/deepstream/config_infer_primary.txt sucessfully

Runtime commands:
	h: Print this help
	q: Quit

	p: Pause
	r: Resume

NOTE: To expand a source in the 2D tiled display and view object details, left-click on the source.
      To go back to the tiled display, right-click anywhere on the window.

** INFO: <bus_callback:194>: Pipeline ready

Opening in BLOCKING MODE
NvMMLiteOpen : Block : BlockType = 261
NVMEDIA: Reading vendor.tegra.display-size : status: 6
NvMMLiteBlockCreate : Block : BlockType = 261

**PERF:  FPS 0 (Avg)	
**PERF:  0.00 (0.00)	
** INFO: <bus_callback:180>: Pipeline running

NvMMLiteOpen : Block : BlockType = 4
===== NVMEDIA: NVENC =====
NvMMLiteBlockCreate : Block : BlockType = 4
deepstream-app: nvdsparsebbox_Yolo.cpp:203: bool NvDsInferParseCustomYolo(const std::vector<NvDsInferLayerInfo>&, const NvDsInferNetworkInfo&, const NvDsInferParseDetectionParams&, std::vector<NvDsInferObjectDetectionInfo>&, const uint&, const uint&): Assertion `layer.inferDims.numDims == 3 || layer.inferDims.numDims == 4' failed.
Aborted (core dumped)`
The tile for display is all black.
How can I fix this problem?

**Comment by beyondli** [comment]
Hi chengzihencai,
thanks for you report, a little busy these days, will check code and feed back soon.

**Comment by beyondli** [comment]
Hi chengzihencai,
I can not reproduce your issue, now I update repo to support Orin AGX. I test both Xavier AGX/Orin AGX , all test cases are test passed fp32/fp16/int8 on deepsteam. For your case. you should  create engine file with command I provided. It should be OK
