### ISSUE TITLE
Self-trained model export error

### ISSUE THREAD

**Issue by penghaoxiao** [beyondli/Yolo_on_Jetson#2]
Namespace(batch_size=1, device='0', dynamic=False, grid=False, img_size=[640, 640], weights='./weights/yolov5s.pt')

Starting ONNX export with onnx 1.12.0...
/home/nvidia/anaconda3/envs/pytorch/lib/python3.8/site-packages/pytorch_quantization/tensor_quant.py:337: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if min_amax < 0:
/home/nvidia/anaconda3/envs/pytorch/lib/python3.8/site-packages/pytorch_quantization/tensor_quant.py:340: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  max_bound = torch.tensor((2.0**(num_bits - 1 + int(unsigned))) - 1.0, device=amax.device)
/home/nvidia/anaconda3/envs/pytorch/lib/python3.8/site-packages/pytorch_quantization/tensor_quant.py:350: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if min_amax <= epsilon:  # Treat amax smaller than minimum representable of fp16 0
ONNX export failure: NYI: Named tensors are not supported with the tracer

Export complete (6.99s). Visualize with https://github.com/lutzroeder/netron.

**Comment by beyondli** [comment]
Hi penghaoxiao,
For you own pt model, maybe you should try different opset with your pytorch version during onnx transfer. in this repo ,opset=13.

**Comment by penghaoxiao** [comment]
> Hi penghaoxiao, For you own pt model, maybe you should try different opset with your pytorch version during onnx transfer. in this repo ,opset=13.

Thanks beyondli, the problem has been solved!
